

name: workflow_dispatch with inputs

on: 
  workflow_dispatch:
    inputs:
      name: 
        description: "Test"
        type: string
        default: "sequ"

      age:
        description: "Age"
        type: number
        required: true




jobs:
  with_input:
    runs-on: ubuntu-latest
    steps:
     - run: echo "hello ${{ inputs.name }}"

     - run: echo "Age is: ${{ inputs.age }}"
