

name: workflow_dispatch with inputs

on: 
  workflow_dispatch:
    inputs:
      name: 
        description: "Test"
        type: string
        default: "sequ"

      age:
        description: "Age"
        type: number
        required: true

      gender:
        description: "Gender"
        type: choice
        options: 
          - Male
          - Female

      status:
       description: "Marrid/Unmarried"
       type: boolean




jobs:
  with_input:
    runs-on: ubuntu-latest
    steps:
      - name: Name 
        run: echo "hello $ {{ inputs.name }} "

      - name: Ages
        run: echo "Age is $ {{ inputs.age }} "


      - name: Gender
        run: echo "Gender:  $ {{ inputs.gender }} "

      - name: Status
        run: echo "Status: $ {{ inputs.status }} "
